catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2
  - semver@6.3.1
packages:
  - packages/*
  - '!docs'

overrides:
  basic-ftp: ^5.3.1
  fast-xml-parser: ^5.7.0
  ip-address: ^10.1.1
  js-yaml: ^3.14.2
  lodash: ^4.17.24
  markdown-it: ^14.1.1
  picomatch: ^4.0.4
  postcss: ^8.5.10
  rollup: 4.59.0
  yaml: ^2.8.3
catalog:
  '@antfu/eslint-config': ^8.3.0
  '@arethetypeswrong/cli': 0.18.2
  '@types/three': ^0.183.1
  '@vitejs/plugin-vue': ^6.0.6
  '@vue/compiler-sfc': ^3.5.32
  bumpp: ^11.1.0
  chrome-remote-interface: ^0.34.0
  eslint: ^10.4.0
  obuild: ^0.4.35
  pinia: ^3.0.4
  puppeteer: ^24.43.1
  typescript: ^6.0.3
  vitest: ^4.1.6

catalogs:
  dependencies:
    '@iconify-json/carbon': latest
    '@iconify-json/icomoon-free': latest
    '@iconify-json/la': latest
    '@iconify-json/logos': latest
    '@iconify-json/mdi': latest
    '@iconify-json/simple-line-icons': latest
    '@nuxt/ui': ^4.6.1
    '@tailwindcss/vite': ^4.2.2
    '@vueuse/core': ^14.2.1
    '@vueuse/router': ^14.2.1
    defu: ^6.1.7
    fuse.js: ^7.3.0
    lightweight-charts: ^5.1.0
    lodash-es: ^4.18.1
    tailwindcss: ^4.2.2
    three: ^0.183.2
    tinyexec: ^1.1.2
    ufo: ^1.6.3
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^32.0.0
    vite: ^8.0.13
    vite-plugin-pages: ^0.33.3
    vue: ^3.5.32

ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - puppeteer

packageExtensions:
  puppeteer-cluster:
    peerDependencies:
      puppeteer-core: '*'
    peerDependenciesMeta:
      puppeteer:
        optional: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: false
  vue-demi: true
